### ISSUE TITLE
primary_skin not built with the image

### ISSUE THREAD

**Issue by elhawaryna** [OpenVisionE2/openvision-development-platform#26]
[When  building the image, there is no skins-octetfhd-primary_skin
http://www.4up4.com/uploads/file_2020-07-22_002452.png
 vu ultimo
DM820
http://www.4up4.com/uploads/file_2020-07-22_003911.png
https://www.mediafire.com/file/6obz0j3rtf1e00o/20200721190045.zip/file

**Comment by elhawaryna** [comment]
**Thanks for answering**

**Comment by persianpros** [comment]
We consider all mipsel boxes as "middleflash" and sometimes even "smallflash" so that's why you won't see our skin, later you could install it from the feeds.

The thing is I don't have the time to find what's not middleflash so for not having boot problems I consider all mipsel boxes as middleflash.

**Comment by elhawaryna** [comment]
Thanks, I got the solution
