### ISSUE TITLE
Add new packages

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#71]
Is there any documentation how to add new packages?
For example I would like now add "ncdu" package for nCurses based du. Could be as optional installable by 'opkg install ncdu'

Will be good to know how to do that

Thanks

**Comment by persianpros** [comment]
It's not hard to add a new recipe if you find it somewhere even the old version then all you need is to adapt it with new OE, for example if you search:

"ncdu openembedded" in google you'll find https://github.com/openembedded/openembedded/tree/master/recipes/ncdu which is for the old OE but hey it's a start!

You can add it to https://github.com/OpenVisionE2/openvision-development-platform/tree/develop/meta-openvision/recipes-core for example then add "ncdu" to our feeds: https://github.com/OpenVisionE2/openvision-development-platform/blob/develop/meta-openvision/recipes-openvision/images/openvision-enigma2-feed.bb#L18

But sometimes there isn't any package and you need to write from scratch and that's why fairbird or norhap ask me to write the new ones not because I'm genius or something but as I'm more familiar with bitbake.

**Comment by petrkr** [comment]
Thank you.. I  need to somehow understand that bb build system, since lot of packages are just includes or rewrites from somewhere else (and I do not know from where).

I tried fast do that ncdu package, just simple rewrite version and checksums and it has some problem at automake tools.. From tar in x86_64 by "tri-command" I can compile it (./configure, make, makeinstall)
But do not know how bitbake know from 4 lines what to do with that.. 

I guess it is something with that "automake" plugin, but maybe I need  to configure it somehow or use different for this simple set-up..

anyway we are closed at homes now (or offices) so have more time to do something

**Comment by persianpros** [comment]
https://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#new-recipe-writing-a-new-recipe

;)
