### ISSUE TITLE
Rpi4 does not work at all

### ISSUE THREAD

**Issue by petrkr** [OpenVisionE2/openvision-development-platform#86]
I guess it's early build, so it will not be good.

First boot is OK, manytimes when is used for example "restart enigma" then it does not appear again (from SSH it is visible it works, but not on primary screen).

Can not play any video.
Tested
 - Remote fallback from sf4008
 - DVB-T2 tuner
 - media player

remote fallback:
  - nothing happends

DVB-T2 tunner
 - nothing happends, EPG is fine also can stream out by using VLC

media player
 - says at every file something like "hardware does not support stream decoding" (tested h264 in mp4, mkv container, hevc in mkv and avi)

SAT->IP client says something about vtuner.

I have here one spare Rpi4, so I can test (or place it to public IPv6 for tests)

**Comment by persianpros** [comment]
You can only watch channels via Open WebIF :+1:

**Comment by 4l3x2k** [comment]
Made some observes. The Idea is great and can be realized. Video / Audio sync will be hassle.

I'am using userland, gst-* and ff* to test. Standard tools. With running enigma I only see one layer with vcgencmd dispanx_list. Wich should be our linux frame buffer. I would expect another layer for Video. Behind gui. Especially for display 2, which is our HDMI output. At the moment the video is put on internal display - csi or whatever it is called.

Background is from
- https://blog.benjdoherty.com/2019/05/21/Exploring-Hardware-Compositing-With-the-Raspberry-Pi/
- https://info-beamer.com/blog/raspberry-pi-hardware-video-scaler

The reported resolution by vcgencmd is somewhat obvious, because rpi3 does not support 4k.
I'am not at the point to get the decoding step of mpegts/mpeg2,h264,h265. Something for the dvbmediasink?
Most of the "play" calls are commented. Thought they are used by the action parts.

At restart of enigma I see call to *hvs* in rpihddevice which may lead to the "... gui ... does not appear again". It is shifted on top. I can see the infobar if I restart enigma and press OK.

We should use start_x as 2nd stage bootloader because it enables some more codecs like flac, theora and Vorbis.
There should be start_x = 1 in config.txt
gpu_mem = 192 is another point to enable most of the vpu.

Last but not least. There is a kernel warning for the rpi firmware restarting the third time.

Output choices and video modes should be more integrated. There is HDMI, CVBS, HDMI2 and on. All with different resolution and encoding.

Something to play with :)
